import { Item, User, Conversation, Message, Mentor, Question, Answer, Review, Notification } from "./types";

export const currentUser: User = {
  id: "user-1",
  firstName: "John",
  lastName: "Smith",
  email: "john.smith@university.ac.uk",
  username: "johnsmith",
  university: "University of Manchester",
  course: "Computer Science",
  yearOfStudy: 2,
  bio: "Second year CS student. Love coding and gaming. Always looking for good deals on textbooks!",
  rating: 4.9,
  itemsListed: 12,
  itemsSold: 8,
  isMentor: false,
  isVerified: true,
  createdAt: "2024-09-15",
};

export const items: Item[] = [
  {
    id: "item-1",
    title: "Calculus: Early Transcendentals 8th Edition",
    description: "Excellent condition calculus textbook. Used for MATH101. Some highlighting but all pages intact. Perfect for first-year maths students.",
    price: 25,
    category: "textbooks",
    condition: "good",
    status: "active",
    images: [],
    sellerId: "user-2",
    sellerName: "Emma Wilson",
    sellerRating: 4.8,
    university: "University of Manchester",
    courseCode: "MATH101",
    createdAt: "2024-12-20",
    views: 45,
    saves: 12,
    isMentorRecommended: true,
  },
  {
    id: "item-2",
    title: "Dell 24\" Monitor",
    description: "Great monitor for studying. 1080p resolution, HDMI and DisplayPort. Minor scratch on back, screen perfect.",
    price: 85,
    category: "electronics",
    condition: "like-new",
    status: "active",
    images: [],
    sellerId: "user-3",
    sellerName: "James Chen",
    sellerRating: 5.0,
    university: "University of Manchester",
    createdAt: "2024-12-18",
    views: 89,
    saves: 23,
    isMentorRecommended: false,
  },
  {
    id: "item-3",
    title: "IKEA Desk Chair",
    description: "Comfortable office chair. Adjustable height. Moving out so need to sell quickly. Collection only.",
    price: 35,
    category: "furniture",
    condition: "good",
    status: "active",
    images: [],
    sellerId: "user-4",
    sellerName: "Sophie Taylor",
    sellerRating: 4.5,
    university: "University of Manchester",
    createdAt: "2024-12-22",
    views: 34,
    saves: 8,
    isMentorRecommended: false,
  },
  {
    id: "item-4",
    title: "Python Programming Notes Bundle",
    description: "Complete notes from COMP101 and COMP201. Includes examples, exercises, and exam prep material. Digital PDF format.",
    price: 8,
    category: "notes",
    condition: "new",
    status: "active",
    images: [],
    sellerId: "user-5",
    sellerName: "Alex Johnson",
    sellerRating: 4.9,
    university: "University of Manchester",
    courseCode: "COMP101",
    createdAt: "2024-12-25",
    views: 156,
    saves: 45,
    isMentorRecommended: true,
  },
  {
    id: "item-5",
    title: "North Face Winter Jacket",
    description: "Size M. Black colour. Worn twice. Too big for me. Great for Manchester weather!",
    price: 60,
    category: "clothing",
    condition: "like-new",
    status: "active",
    images: [],
    sellerId: "user-6",
    sellerName: "Oliver Brown",
    sellerRating: 4.7,
    university: "University of Manchester",
    createdAt: "2024-12-19",
    views: 67,
    saves: 15,
    isMentorRecommended: false,
  },
  {
    id: "item-6",
    title: "Sony WH-1000XM4 Headphones",
    description: "Noise cancelling headphones. Perfect for library study sessions. Includes case and charging cable.",
    price: 120,
    category: "electronics",
    condition: "good",
    status: "active",
    images: [],
    sellerId: "user-2",
    sellerName: "Emma Wilson",
    sellerRating: 4.8,
    university: "University of Manchester",
    createdAt: "2024-12-21",
    views: 203,
    saves: 56,
    isMentorRecommended: true,
  },
  {
    id: "item-7",
    title: "Introduction to Algorithms (CLRS)",
    description: "The classic algorithms textbook. 3rd edition. Essential for CS students. Some wear on cover.",
    price: 30,
    category: "textbooks",
    condition: "fair",
    status: "active",
    images: [],
    sellerId: "user-7",
    sellerName: "Mia Davis",
    sellerRating: 4.6,
    university: "University of Manchester",
    courseCode: "COMP202",
    createdAt: "2024-12-23",
    views: 78,
    saves: 22,
    isMentorRecommended: true,
  },
  {
    id: "item-8",
    title: "Mini Fridge",
    description: "Perfect for dorm room. 45L capacity. Works perfectly. Moving to flat with kitchen.",
    price: 45,
    category: "furniture",
    condition: "good",
    status: "active",
    images: [],
    sellerId: "user-8",
    sellerName: "Noah Wilson",
    sellerRating: 4.4,
    university: "University of Manchester",
    createdAt: "2024-12-24",
    views: 91,
    saves: 19,
    isMentorRecommended: false,
  },
  {
    id: "item-9",
    title: "Organic Chemistry Notes",
    description: "Comprehensive notes covering all CHEM201 topics. Helped me get a first!",
    price: 12,
    category: "notes",
    condition: "new",
    status: "active",
    images: [],
    sellerId: "user-9",
    sellerName: "Isabella Martinez",
    sellerRating: 5.0,
    university: "University of Manchester",
    courseCode: "CHEM201",
    createdAt: "2024-12-26",
    views: 134,
    saves: 38,
    isMentorRecommended: true,
  },
  {
    id: "item-10",
    title: "Mechanical Keyboard",
    description: "Cherry MX Blue switches. RGB lighting. Great for coding. Includes wrist rest.",
    price: 55,
    category: "electronics",
    condition: "like-new",
    status: "active",
    images: [],
    sellerId: "user-10",
    sellerName: "Liam Thompson",
    sellerRating: 4.8,
    university: "University of Manchester",
    createdAt: "2024-12-17",
    views: 112,
    saves: 28,
    isMentorRecommended: false,
  },
  {
    id: "item-11",
    title: "Physics Lab Coat",
    description: "White lab coat, size S. Required for physics practicals. Used for one semester.",
    price: 10,
    category: "clothing",
    condition: "good",
    status: "active",
    images: [],
    sellerId: "user-11",
    sellerName: "Charlotte White",
    sellerRating: 4.3,
    university: "University of Manchester",
    createdAt: "2024-12-16",
    views: 23,
    saves: 5,
    isMentorRecommended: false,
  },
  {
    id: "item-12",
    title: "Desk Lamp with USB Port",
    description: "LED desk lamp with adjustable brightness. Built-in USB charging port. Perfect for late night studying.",
    price: 18,
    category: "electronics",
    condition: "new",
    status: "active",
    images: [],
    sellerId: "user-12",
    sellerName: "Ethan Harris",
    sellerRating: 4.9,
    university: "University of Manchester",
    createdAt: "2024-12-27",
    views: 45,
    saves: 11,
    isMentorRecommended: false,
  },
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    participantId: "user-2",
    participantName: "Emma Wilson",
    lastMessage: "Is the calculus textbook still available?",
    lastMessageTime: "2m ago",
    unread: true,
    itemId: "item-1",
    itemTitle: "Calculus: Early Transcendentals",
  },
  {
    id: "conv-2",
    participantId: "user-3",
    participantName: "James Chen",
    lastMessage: "Thanks! I'll pick it up tomorrow at 3pm",
    lastMessageTime: "1h ago",
    unread: false,
    itemId: "item-2",
    itemTitle: "Dell 24\" Monitor",
  },
  {
    id: "conv-3",
    participantId: "user-4",
    participantName: "Sophie Taylor",
    lastMessage: "Can you do £30 for the chair?",
    lastMessageTime: "3h ago",
    unread: false,
    itemId: "item-3",
    itemTitle: "IKEA Desk Chair",
  },
  {
    id: "conv-4",
    participantId: "user-5",
    participantName: "Alex Johnson",
    lastMessage: "Perfect, see you at the library!",
    lastMessageTime: "1d ago",
    unread: false,
  },
  {
    id: "conv-5",
    participantId: "user-6",
    participantName: "Oliver Brown",
    lastMessage: "Is the jacket waterproof?",
    lastMessageTime: "2d ago",
    unread: false,
    itemId: "item-5",
    itemTitle: "North Face Winter Jacket",
  },
];

export const messages: Record<string, Message[]> = {
  "conv-1": [
    { id: "msg-1", conversationId: "conv-1", senderId: "user-2", content: "Hi! I saw your listing for the calculus textbook", sentAt: "10:30 AM", isRead: true },
    { id: "msg-2", conversationId: "conv-1", senderId: "user-1", content: "Hey! Yes, it's still available", sentAt: "10:32 AM", isRead: true },
    { id: "msg-3", conversationId: "conv-1", senderId: "user-2", content: "Great! Is there any highlighting in it?", sentAt: "10:33 AM", isRead: true },
    { id: "msg-4", conversationId: "conv-1", senderId: "user-1", content: "Some chapters have highlighting but it's minimal and doesn't affect readability", sentAt: "10:35 AM", isRead: true },
    { id: "msg-5", conversationId: "conv-1", senderId: "user-2", content: "Is the calculus textbook still available?", sentAt: "10:40 AM", isRead: false },
  ],
  "conv-2": [
    { id: "msg-6", conversationId: "conv-2", senderId: "user-3", content: "Hi, is the monitor still for sale?", sentAt: "Yesterday", isRead: true },
    { id: "msg-7", conversationId: "conv-2", senderId: "user-1", content: "Yes it is! Are you interested?", sentAt: "Yesterday", isRead: true },
    { id: "msg-8", conversationId: "conv-2", senderId: "user-3", content: "Definitely! Can I pick it up tomorrow?", sentAt: "Yesterday", isRead: true },
    { id: "msg-9", conversationId: "conv-2", senderId: "user-1", content: "Sure, what time works for you?", sentAt: "Yesterday", isRead: true },
    { id: "msg-10", conversationId: "conv-2", senderId: "user-3", content: "Thanks! I'll pick it up tomorrow at 3pm", sentAt: "1h ago", isRead: true },
  ],
};

export const mentors: Mentor[] = [
  {
    id: "mentor-1",
    userId: "user-5",
    name: "Alex Johnson",
    university: "University of Manchester",
    course: "Computer Science",
    bio: "Final year CS student. Happy to help with programming, algorithms, and career advice. Previously interned at Google.",
    expertise: ["Python", "Algorithms", "Data Structures", "Machine Learning"],
    rating: 4.9,
    endorsements: 45,
    totalAnswers: 128,
    helpfulAnswers: 115,
    isVerified: true,
  },
  {
    id: "mentor-2",
    userId: "user-9",
    name: "Isabella Martinez",
    university: "University of Manchester",
    course: "Chemistry",
    bio: "PhD student in Organic Chemistry. Can help with any chemistry questions from first year to masters level.",
    expertise: ["Organic Chemistry", "Lab Techniques", "Research Methods"],
    rating: 5.0,
    endorsements: 62,
    totalAnswers: 89,
    helpfulAnswers: 87,
    isVerified: true,
  },
  {
    id: "mentor-3",
    userId: "user-13",
    name: "David Kim",
    university: "University of Manchester",
    course: "Mathematics",
    bio: "Teaching assistant for MATH201. Love making complex maths concepts simple and accessible.",
    expertise: ["Calculus", "Linear Algebra", "Statistics", "Probability"],
    rating: 4.8,
    endorsements: 38,
    totalAnswers: 156,
    helpfulAnswers: 142,
    isVerified: true,
  },
  {
    id: "mentor-4",
    userId: "user-14",
    name: "Sarah Thompson",
    university: "University of Manchester",
    course: "Medicine",
    bio: "Third year medical student. Can help with anatomy, physiology, and med school applications.",
    expertise: ["Anatomy", "Physiology", "UKCAT Prep", "Med School Applications"],
    rating: 4.7,
    endorsements: 29,
    totalAnswers: 67,
    helpfulAnswers: 58,
    isVerified: true,
  },
  {
    id: "mentor-5",
    userId: "user-15",
    name: "Michael Brown",
    university: "University of Manchester",
    course: "Business",
    bio: "MBA student with 5 years industry experience. Happy to discuss business concepts and career paths.",
    expertise: ["Finance", "Marketing", "Entrepreneurship", "Career Advice"],
    rating: 4.6,
    endorsements: 21,
    totalAnswers: 43,
    helpfulAnswers: 38,
    isVerified: false,
  },
  {
    id: "mentor-6",
    userId: "user-16",
    name: "Emily Chen",
    university: "University of Manchester",
    course: "Physics",
    bio: "Postgraduate researcher in quantum computing. Can help with physics and maths questions.",
    expertise: ["Quantum Mechanics", "Classical Mechanics", "Electromagnetism"],
    rating: 4.9,
    endorsements: 34,
    totalAnswers: 78,
    helpfulAnswers: 72,
    isVerified: true,
  },
];

export const questions: Question[] = [
  {
    id: "q-1",
    title: "Best resources for learning Python as a beginner?",
    content: "I'm starting COMP101 next semester and want to get a head start on Python. What resources would you recommend for a complete beginner?",
    askerId: "user-11",
    askerName: "Charlotte White",
    category: "academic",
    courseCode: "COMP101",
    status: "answered",
    createdAt: "2024-12-26",
    answerCount: 3,
  },
  {
    id: "q-2",
    title: "How to prepare for organic chemistry exams?",
    content: "Struggling with organic chemistry. Any tips for memorizing reactions and mechanisms? The exam is in 3 weeks.",
    askerId: "user-8",
    askerName: "Noah Wilson",
    category: "academic",
    courseCode: "CHEM201",
    status: "open",
    createdAt: "2024-12-27",
    answerCount: 1,
  },
  {
    id: "q-3",
    title: "Which calculus textbook should I buy?",
    content: "There are several calculus textbooks listed here. Which one would you recommend for MATH101? Stewart or Thomas?",
    askerId: "user-12",
    askerName: "Ethan Harris",
    category: "textbook-recommendation",
    courseCode: "MATH101",
    status: "answered",
    createdAt: "2024-12-25",
    answerCount: 4,
  },
  {
    id: "q-4",
    title: "Tips for managing coursework and part-time job?",
    content: "I need to work part-time to support myself but I'm worried about falling behind on coursework. Any advice from students who've done both?",
    askerId: "user-10",
    askerName: "Liam Thompson",
    category: "student-life",
    status: "answered",
    createdAt: "2024-12-24",
    answerCount: 5,
  },
  {
    id: "q-5",
    title: "Should I take COMP301 or COMP302?",
    content: "For my third year electives, I'm torn between AI (COMP301) and Distributed Systems (COMP302). Which is more useful for software engineering careers?",
    askerId: "user-7",
    askerName: "Mia Davis",
    category: "course-advice",
    status: "open",
    createdAt: "2024-12-28",
    answerCount: 2,
  },
];

export const answers: Record<string, Answer[]> = {
  "q-1": [
    { id: "a-1", questionId: "q-1", mentorId: "mentor-1", mentorName: "Alex Johnson", content: "I'd highly recommend starting with 'Automate the Boring Stuff with Python' - it's free online and very practical. Also, Codecademy has a great interactive Python course. Once you're comfortable with basics, try some simple projects like a calculator or a to-do list app.", helpfulCount: 23, isEndorsed: true, createdAt: "2024-12-26" },
    { id: "a-2", questionId: "q-1", mentorId: "mentor-3", mentorName: "David Kim", content: "Python Crash Course by Eric Matthes is excellent for beginners. It has hands-on projects that really help cement the concepts. Also, don't underestimate the official Python tutorial at docs.python.org.", helpfulCount: 15, isEndorsed: false, createdAt: "2024-12-26" },
    { id: "a-3", questionId: "q-1", mentorId: "mentor-6", mentorName: "Emily Chen", content: "Start with basics but don't spend too long on tutorials. The best way to learn is by doing! Pick a small project idea and Google your way through it. That's how most programmers learn.", helpfulCount: 18, isEndorsed: false, createdAt: "2024-12-27" },
  ],
  "q-2": [
    { id: "a-4", questionId: "q-2", mentorId: "mentor-2", mentorName: "Isabella Martinez", content: "For organic chemistry, understanding is key over memorization. Focus on understanding WHY reactions happen (electron movement, stability) rather than memorizing each one. Draw mechanisms repeatedly - muscle memory helps a lot. I also recommend making reaction maps grouping similar reactions together.", helpfulCount: 12, isEndorsed: true, createdAt: "2024-12-27" },
  ],
  "q-3": [
    { id: "a-5", questionId: "q-3", mentorId: "mentor-3", mentorName: "David Kim", content: "Stewart's Calculus is the standard text for MATH101 and what most lecturers reference. I'd go with that. Thomas is also good but Stewart's explanations are clearer in my opinion. You can find older editions much cheaper - the content barely changes between editions.", helpfulCount: 8, isEndorsed: true, createdAt: "2024-12-25" },
    { id: "a-6", questionId: "q-3", mentorId: "mentor-6", mentorName: "Emily Chen", content: "Either works fine! Stewart is more popular here. Pro tip: check if there's a PDF version in the library's online resources before buying.", helpfulCount: 5, isEndorsed: false, createdAt: "2024-12-25" },
  ],
};

export const reviews: Review[] = [
  { id: "r-1", reviewerId: "user-3", reviewerName: "James Chen", rating: 5, comment: "Great seller! Item exactly as described. Quick response.", createdAt: "2024-12-20" },
  { id: "r-2", reviewerId: "user-4", reviewerName: "Sophie Taylor", rating: 5, comment: "Very friendly and helpful. Would buy from again!", createdAt: "2024-12-18" },
  { id: "r-3", reviewerId: "user-6", reviewerName: "Oliver Brown", rating: 4, comment: "Good transaction. Item was in good condition.", createdAt: "2024-12-15" },
  { id: "r-4", reviewerId: "user-8", reviewerName: "Noah Wilson", rating: 5, comment: "Excellent communication. Highly recommended seller.", createdAt: "2024-12-12" },
];

export const notifications: Notification[] = [
  { id: "n-1", type: "message", title: "New message", description: "Emma Wilson sent you a message about Calculus Textbook", isRead: false, createdAt: "2m ago", link: "/messages" },
  { id: "n-2", type: "sale", title: "Item sold!", description: "Your Dell Monitor has been marked as sold", isRead: false, createdAt: "1h ago", link: "/profile/listings" },
  { id: "n-3", type: "review", title: "New review", description: "James Chen left you a 5-star review", isRead: true, createdAt: "2h ago", link: "/profile" },
  { id: "n-4", type: "question", title: "New answer", description: "Alex Johnson answered your question about Python", isRead: true, createdAt: "1d ago", link: "/questions/q-1" },
  { id: "n-5", type: "endorsement", title: "Item endorsed!", description: "A mentor endorsed your Python Notes listing", isRead: true, createdAt: "2d ago", link: "/marketplace/item-4" },
];

export const userListings: Item[] = items.filter(item => item.sellerId === "user-1" || ["item-1", "item-4", "item-7", "item-9"].includes(item.id)).slice(0, 4);

export const categories = [
  { value: "all", label: "All" },
  { value: "textbooks", label: "Textbooks" },
  { value: "electronics", label: "Electronics" },
  { value: "furniture", label: "Furniture" },
  { value: "clothing", label: "Clothing" },
  { value: "notes", label: "Notes" },
  { value: "other", label: "Other" },
];

export const conditions = [
  { value: "all", label: "All Conditions" },
  { value: "new", label: "New" },
  { value: "like-new", label: "Like New" },
  { value: "good", label: "Good" },
  { value: "fair", label: "Fair" },
  { value: "poor", label: "Poor" },
];
